theme: just-the-docs
baseurl: /js-visualize-components-samples
search_enabled: false
exclude:
  - react-app-render/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo-white-tj.svg"

plugins:
  - jekyll-seo-tag
